fix: tools: a39x: fixed compilation issue in a39x PHY library
	- Ungeneric specific SoC tables was called by generic code, which
	  lead to compilation error without optimization (BIN_HDR_DEBUG=1)
	- Fixed by relocating specific functions into SoC specific code (sysEnv)

Change-Id: Idbe2291c9c23c0c8a45964cd4d8189b4e18bae26
Signed-off-by: Margarita Granov <margra@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/13530
Reviewed-by: Omri Itach <omrii@marvell.com>
Tested-by: Omri Itach <omrii@marvell.com>