ALP: Fix compilation error, caused by replacing snprintf instead of sprintf
Change-Id: I091106f63fa1d82a183a534a84c42a8ab10edf3d
Reviewed-on: http://vgitil04.il.marvell.com:8080/1435
Reviewed-by: Kosta Zertsekel <konszert@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>
Tested-by: Omri Itach <omrii@marvell.com>