fixed FPGA compilation error, caused by enabling the MV_INCLUDE_GIG_ETH define
Change-Id: Ie1850249ddb9651ab719fa221ba0a75d69f00c7b
Reviewed-on: http://vgitil04.il.marvell.com:8080/1220
Reviewed-by: Kosta Zertsekel <konszert@marvell.com>
Reviewed-by: Eran Ben-Avi <benavi@marvell.com>
Tested-by: Eran Ben-Avi <benavi@marvell.com>