fix: alp, a375: fixed compilation warning with legacy DDR libraries
	relevant only for internal legacy DDR libraries.
	caused by redefinition of DB macro.
	The macro should be defined only in source files.

Change-Id: I6177dbf10c5601fd8cfa1a2e805c7e5b72a445e7
Signed-off-by: Igor Patrik <igorp@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/14572
Reviewed-by: Haim Boot <hayim@marvell.com>
Tested-by: Star_Automation <star@marvell.com>
Reviewed-by: Omri Itach <omrii@marvell.com>
Reviewed-on: http://vgitil04.il.marvell.com:8080/14681